// import './example/basic-type'
// import './example/symbol'
// import './example/interface'
// import './example/function'
// import './example/generics'
// import './example/es6-class-1'
// import './example/es6-class-2'
// import './example/ts-class'
import './example/enum'